### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by carstorm** [p455w0rd/MorphTweaks#1]
https://pastebin.com/Dhvnig4a

I believe its cause by you trying to call something from Twilight Forest w/o making sure that Twilight Forest is installed?

**Comment by Morpheus1101** [comment]
Can Confirm this indeed does occur

**Comment by p455w0rd** [comment]
yeah i got a lot on my plate..i forget that check..will get a fix out asap..thanks for reporting :)

**Comment by carstorm** [comment]
Thanks for quick response, once this updates it will be added to our modpack and pushed live ☺

**Comment by Morpheus1101** [comment]
Fixed in new release
