### ISSUE TITLE
[1.12.2] Ender Dragon hover change

### ISSUE THREAD

**Issue by Morpheus1101** [p455w0rd/MorphTweaks#11]
Have an option to change the enderdragon to not hover over the center untill its death event. ive been told this  is indeed possible and thankfully dosent require any ASM

**Comment by p455w0rd** [comment]
so I looked at it..and it will require an access transformer at minimum to remove the hover phase from the phase list..this will have to wait until next update as it will take some to to ensure it works correctly

**Comment by Morpheus1101** [comment]
No longer an issue etc etc etc
