### ISSUE TITLE
Massive mushroom island spam with Thaumcraft

### ISSUE THREAD

**Issue by Thedrummonger** [p455w0rd/MorphTweaks#12]
With thaumcraft and morphtweaks installed Mushroom Islands are taking over about >25% of the world as seem in the attached picture.
![2018-05-08_12 26 34](https://user-images.githubusercontent.com/16329331/39772648-66e1fea2-52bb-11e8-883e-f019cb237279.png)

Here are my log files:
https://pastebin.com/YYuUJ1UX

The only mods I have installed are:
Morphtweaks: 1.12-1.3.6
Thaumcraft; 1.12.6.1.BETA13
Natures Compass: 1.12.2-1.5.1
CodeChicken Lib: 1.12.2-3.1.8.341
Baubles: 1.12-1.5.2
Forge: 14.23.3.2679

If i had to guess I would guess this had to do with the biomes added by morph tweaks, the biome ocean replacement and biome river replacement. Would it be possible to have a config option to disable them? Not only would it probably fix the issue temporarily but I don't actually want them in my instance since I am only using this mod for the twilight forest liquid replacement.

Thanks in advance.

**Comment by p455w0rd** [comment]
added config in coming update
