### ISSUE TITLE
Crash When Trying to enter Twilight Forest

### ISSUE THREAD

**Issue by Danymaddox** [p455w0rd/MorphTweaks#14]
Hi! I'm trying to create a custom portal to the Twilight Forest using Liquid Death as fluid and Void Seed as catalyst, both from Thaumcraft 6, but I'm getting this crash:

https://pastebin.com/PBAzQxdK

Forge: 14.23.5.2838
TwilightForest: 1.12.2-3.9.974
MorphTweaks: 1.12-1.3.8
Thaumcraft: 1.12.2-6.1.BETA26

If you need more information, please contact me :)

**Comment by p455w0rd** [comment]
thanks..wil look into it

**Comment by Morpheus1101** [comment]
This mod is no longer supported nor is the minecraft version.
