### ISSUE TITLE
[REQUEST] Allow via configs custom commands to redirect

### ISSUE THREAD

**Issue by carstorm** [p455w0rd/MorphTweaks#3]
Allow people to set up custom commands to run other commands that the player normally wouldn't have access to.

For example if a player types "/tpspawn" it would actually run "/tpj 10" even if the player couldn't type "/tpj 10" directly.

Though it would be harder, it would be a nice bonus if you could override existing commands such as (in above example) hijacking the "/spawn" command.

**Comment by Morpheus1101** [comment]
Not really something thats valid for what this mod is intended for
