### ISSUE TITLE
*REQUEST* Voidifier Block Info

### ISSUE THREAD

**Issue by mahilo3550** [p455w0rd/MorphTweaks#4]
I have an idea of what this block does, but not exactly how it works. Not always so cut and dry when it comes to Minecraft mods. Anyway you could add an explanation on the CurseForge page?

**Comment by Morpheus1101** [comment]
The block voids any an all items either piped in or Shift + Clicked into the slot .. essentially making it a large Trashcan

**Comment by p455w0rd** [comment]
it voids all items, fluids, and Forge Energy..it says this on the tooltip
