### ISSUE TITLE
Shift-clicking a book into the gui causes crash (Forge 14.23.1.2590)

### ISSUE THREAD

**Issue by saramaebee** [p455w0rd/MorphTweaks#5]
MMD Public Pack - Reloaded
MorphTweaks (1.12-1.3.4)

Maybe it isn't repeatable, but my system took 20 minutes to recover after this, so I don't wanna try again)

I have no other mods such as optifine or anything else, only the default files for the pack.

**Comment by Morpheus1101** [comment]
Tested this myself with the same pack, shift clicked thew book in an out of the gui multiple times an nothing like this occured.  I am using Forge *.2606 however

Edit: Re-Tested using Forge *.2590 an could not again re-create this issue as described

**Comment by Morpheus1101** [comment]
I was able to reproduce this with Shift + Click a wheat seed & Chicken Egg into the Adv Enchanter, the game froze but was still active an the server eventually kicked me for being idle.

Im guessing there is no checks to see if item being shift+ clicked in, is a valid item.
