### ISSUE TITLE
some suggestions

### ISSUE THREAD

**Issue by 0Navis0** [p455w0rd/MorphTweaks#8]
**Hunger quencher:** I already talked about this one, work same than thirst quencer, but with food.

**Portable voidifier:** It would be a mixt of voidifer and danknull, it would delete all fluids, blocks or items right clicked on it or gotten in the inventory, with a filter for selectioning which blocks or fluids to voidify.

**Automatic advanced enchanter:** It would enable to automate the enchantments with pipes and chests.

Integration of dank/null in the mod, potentially automatic enchanting table, and disenchanting and automatic disenchanting table.

**Comment by p455w0rd** [comment]
just a note to morpheus..i requested that @Hypsellis make this issue..don't close it pls
